[project]
name = "ai-agents-v1"
version = "0.1.1"
description = "FLX playground agents"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openapi>=2.0.0",
    "python-dotenv>=1.1.1",
    "requests>=2.32.5",
]
